
name: shell

on: [push, workflow_dispatch]

jobs:
  runshell:
    runs-on: macos-10.15
    name: Start a Solaris shell
    steps:
    - name: Starting a solaris VM, please wait. It may take 5 minutes
      id: shell
      uses: vmactions/solaris-vm@main
      with:
        run: |
          pwd
          ls -lah
          whoami
          env
          cat /etc/release
          echo "OK"
    - name: Sleep
      run: sleep 5
    - uses: neilpang/debugger-action@master

